/**
 * Admin product create/edit multi-step form.
 */
export function productWizard(config = {}) {
    const formData = {
        type: 'simple',
        brand_id: '',
        name_en: '',
        name_ar: '',
        slug: '',
        sku: '',
        description_en: '',
        description_ar: '',
        price: '0',
        stock: '',
        is_in_stock: true,
        discount: '0',
        discount_type: 'percentage',
        category_ids: [],
        related_products: [],
        is_active: true,
        is_featured: false,
        is_new: false,
        is_approved: true,
        is_bookable: false,
        variantOptions: {},
        ...(config.formData ?? {}),
    };

    if (!formData.variantOptions || typeof formData.variantOptions !== 'object') {
        formData.variantOptions = {};
    }

    const catalogVariants = config.catalogVariants ?? [];
    const initialRows = config.existingProductVariants ?? [];
    const quickCatalogVariantUrl = config.quickCatalogVariantUrl ?? '';
    const quickVariantOptionUrl = config.quickVariantOptionUrl ?? '';
    const nextSkuUrl = config.nextSkuUrl ?? '';

    return {
        mode: config.mode ?? 'create',
        currentStep: 1,
        formData,
        catalogVariants,
        productVariants: [],
        optionSearchQueries: {},
        newOptionForms: {},
        newCatalogVariant: { name_en: '', name_ar: '' },
        catalogVariantSaving: false,
        optionSavingId: null,
        skuAutoGenerated: false,
        quickCatalogVariantUrl,
        quickVariantOptionUrl,
        nextSkuUrl,
        thumbnailPreview: config.thumbnailPreview ?? null,
        thumbnailFile: null,
        selectedImages: [],
        existingImages: config.existingImages ?? [],

        get isEdit() {
            return this.mode === 'edit';
        },

        get isVariable() {
            return this.formData.type === 'variable';
        },

        get stepFlow() {
            const steps = ['basic', 'pricing'];
            if (this.isVariable) {
                steps.push('variants');
            }
            steps.push('categories', 'images', 'related');

            return steps;
        },

        get totalSteps() {
            return this.stepFlow.length;
        },

        get currentStepKey() {
            return this.stepFlow[this.currentStep - 1] ?? 'basic';
        },

        init() {
            if (this.formData.name_en && !this.isEdit) {
                this.generateSlug();
            }

            this.initializeVariantOptions();
            this.initializeOptionForms();

            if (!this.isEdit) {
                this.loadNextSku();
            }

            if (initialRows.length > 0) {
                this.rebuildVariantOptionsFromRows(initialRows);
                this.generateProductVariants(initialRows);
            }
        },

        initializeVariantOptions() {
            const options = { ...(this.formData.variantOptions ?? {}) };

            this.catalogVariants.forEach((variant) => {
                const key = String(variant.id);
                if (!Array.isArray(options[key])) {
                    options[key] = [];
                }
            });

            this.formData.variantOptions = options;
        },

        initializeOptionForms() {
            const forms = { ...(this.newOptionForms ?? {}) };
            const queries = { ...(this.optionSearchQueries ?? {}) };

            this.catalogVariants.forEach((variant) => {
                const key = String(variant.id);
                if (!forms[key]) {
                    forms[key] = { name_en: '', name_ar: '' };
                }
                if (queries[key] === undefined) {
                    queries[key] = '';
                }
            });

            this.newOptionForms = forms;
            this.optionSearchQueries = queries;
        },

        csrfToken() {
            return document.querySelector('meta[name="csrf-token"]')?.content ?? '';
        },

        async loadNextSku() {
            if (!this.nextSkuUrl || this.isEdit) {
                return;
            }

            try {
                const response = await fetch(this.nextSkuUrl, {
                    headers: { Accept: 'application/json' },
                });

                if (!response.ok) {
                    return;
                }

                const payload = await response.json();

                if (payload.sku) {
                    this.formData.sku = payload.sku;
                    this.skuAutoGenerated = true;

                    if (this.formData.type === 'variable') {
                        this.generateProductVariants();
                    }
                }
            } catch {
                // Keep manual entry available if the request fails.
            }
        },

        isOptionSelected(variantId, optionId) {
            return this.isVariantOptionSelected(variantId, optionId);
        },

        optionLabel(optionId) {
            const option = this.findCatalogOption(optionId);

            return option?.name ?? option?.name_en ?? `#${optionId}`;
        },

        filteredCatalogOptions(catalogVariant) {
            const query = (this.optionSearchQueries[String(catalogVariant.id)] ?? '').trim().toLowerCase();
            const options = catalogVariant.options ?? [];

            if (!query) {
                return options;
            }

            return options.filter((option) => {
                const haystack = [
                    option.name,
                    option.name_en,
                    option.name_ar,
                    option.code,
                ].filter(Boolean).join(' ').toLowerCase();

                return haystack.includes(query);
            });
        },

        async createCatalogVariant() {
            const nameEn = (this.newCatalogVariant.name_en ?? '').trim();
            const nameAr = (this.newCatalogVariant.name_ar ?? '').trim();

            if (!nameEn || !nameAr || !this.quickCatalogVariantUrl) {
                return;
            }

            this.catalogVariantSaving = true;

            try {
                const response = await fetch(this.quickCatalogVariantUrl, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        Accept: 'application/json',
                        'X-CSRF-TOKEN': this.csrfToken(),
                    },
                    body: JSON.stringify({
                        name: { en: nameEn, ar: nameAr },
                    }),
                });

                if (!response.ok) {
                    return;
                }

                const payload = await response.json();
                this.catalogVariants = [...this.catalogVariants, payload.variant];
                this.newCatalogVariant = { name_en: '', name_ar: '' };
                this.initializeVariantOptions();
                this.initializeOptionForms();
            } finally {
                this.catalogVariantSaving = false;
            }
        },

        async createCatalogOption(variantId) {
            const key = String(variantId);
            const form = this.newOptionForms[key] ?? { name_en: '', name_ar: '' };
            const nameEn = (form.name_en ?? '').trim();
            const nameAr = (form.name_ar ?? '').trim();

            if (!nameEn || !nameAr || !this.quickVariantOptionUrl) {
                return;
            }

            this.optionSavingId = key;

            try {
                const response = await fetch(this.quickVariantOptionUrl, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        Accept: 'application/json',
                        'X-CSRF-TOKEN': this.csrfToken(),
                    },
                    body: JSON.stringify({
                        variant_id: Number(variantId),
                        name: { en: nameEn, ar: nameAr },
                    }),
                });

                if (!response.ok) {
                    return;
                }

                const payload = await response.json();
                this.catalogVariants = this.catalogVariants.map((variant) => {
                    if (String(variant.id) !== String(payload.variant_id)) {
                        return variant;
                    }

                    const options = [...(variant.options ?? []), payload.option];

                    return { ...variant, options };
                });

                this.newOptionForms[key] = { name_en: '', name_ar: '' };
                this.toggleVariantOption(variantId, payload.option.id, true);
            } finally {
                this.optionSavingId = null;
            }
        },

        rebuildVariantOptionsFromRows(rows) {
            this.initializeVariantOptions();

            rows.forEach((row) => {
                const optionIds = row.option_ids ?? Object.values(row.options_by_variant ?? {}).filter(Boolean);

                optionIds.forEach((optionId) => {
                    const catalogVariant = this.catalogVariants.find((variant) => (
                        variant.options?.some((opt) => String(opt.id) === String(optionId))
                    ));

                    if (!catalogVariant) {
                        return;
                    }

                    const variantId = String(catalogVariant.id);
                    const optionIdStr = String(optionId);

                    if (!this.formData.variantOptions[variantId].includes(optionIdStr)) {
                        this.formData.variantOptions[variantId].push(optionIdStr);
                    }
                });
            });
        },

        isVariantOptionSelected(variantId, optionId) {
            const selected = this.formData.variantOptions[String(variantId)] ?? [];

            return selected.map(String).includes(String(optionId));
        },

        hasAnyVariantOptionSelected() {
            return Object.values(this.formData.variantOptions ?? {}).some(
                (options) => Array.isArray(options) && options.length > 0,
            );
        },

        toggleVariantOption(variantId, optionId, isChecked) {
            const variantKey = String(variantId);

            if (!this.formData.variantOptions[variantKey]) {
                this.formData.variantOptions = {
                    ...this.formData.variantOptions,
                    [variantKey]: [],
                };
            }

            const optionIdStr = String(optionId);
            const currentOptions = [...(this.formData.variantOptions[variantKey] ?? [])];

            if (isChecked) {
                if (!currentOptions.includes(optionIdStr)) {
                    this.formData.variantOptions[variantKey] = [...currentOptions, optionIdStr];
                }
            } else {
                this.formData.variantOptions[variantKey] = currentOptions.filter((id) => id !== optionIdStr);
            }

            this.generateProductVariants();
        },

        generateProductVariants(seedRows = null) {
            if (this.formData.type !== 'variable') {
                this.productVariants = [];

                return;
            }

            if (!this.hasAnyVariantOptionSelected()) {
                this.productVariants = [];

                return;
            }

            const existingByCombo = {};
            const sourceRows = seedRows ?? this.productVariants;

            sourceRows.forEach((row) => {
                const normalized = this.normalizeVariantRow(row);
                const key = this.comboKey(normalized.option_ids);

                if (key) {
                    existingByCombo[key] = normalized;
                }
            });

            const combinations = this.buildVariantCombinations();

            this.productVariants = combinations.map((combo) => {
                const key = this.comboKey(combo.option_ids);
                const existing = existingByCombo[key];
                const autoSku = this.generateRowSku(combo.option_ids);
                const labels = this.optionLabelsForIds(combo.option_ids);
                const displayName = labels.en || labels.ar || '';

                if (existing) {
                    const previousAutoSku = this.generateRowSku(existing.option_ids ?? []);
                    const shouldRefreshSku = !existing.sku?.trim()
                        || existing.sku === previousAutoSku
                        || (this.formData.sku && String(existing.sku).startsWith(`${this.formData.sku}-`));

                    return {
                        ...existing,
                        _key: `pv_${key}`,
                        option_ids: combo.option_ids,
                        options_by_variant: combo.options_by_variant,
                        name: existing.name || displayName,
                        name_en: existing.name_en || labels.en,
                        name_ar: existing.name_ar || labels.ar,
                        sku: shouldRefreshSku ? autoSku : existing.sku,
                    };
                }

                return {
                    _key: `pv_${key}`,
                    id: '',
                    name: displayName,
                    sku: autoSku,
                    name_en: labels.en,
                    name_ar: labels.ar,
                    price: this.formData.price ?? '0',
                    stock: '',
                    is_in_stock: true,
                    discount: '0',
                    discount_type: 'percentage',
                    is_active: true,
                    thumbnailPreview: null,
                    thumbnailFile: null,
                    options_by_variant: combo.options_by_variant,
                    option_ids: combo.option_ids,
                };
            });
        },

        buildVariantCombinations() {
            const variantsWithOptions = this.catalogVariants.filter((variant) => {
                const selected = this.formData.variantOptions[String(variant.id)] ?? [];

                return selected.length > 0;
            });

            if (variantsWithOptions.length === 0) {
                return [];
            }

            const optionArrays = variantsWithOptions.map((variant) => {
                const selectedOptionIds = (this.formData.variantOptions[String(variant.id)] ?? [])
                    .map((id) => String(id));

                return (variant.options ?? []).filter((option) => selectedOptionIds.includes(String(option.id)));
            });

            const combinations = [];

            const generate = (index, current) => {
                if (index === optionArrays.length) {
                    const optionIds = current.map((option) => String(option.id));
                    const optionsByVariant = {};

                    current.forEach((option, optionIndex) => {
                        const variant = variantsWithOptions[optionIndex];
                        optionsByVariant[String(variant.id)] = String(option.id);
                    });

                    combinations.push({
                        option_ids: optionIds,
                        options_by_variant: optionsByVariant,
                    });

                    return;
                }

                optionArrays[index].forEach((option) => {
                    generate(index + 1, [...current, option]);
                });
            };

            generate(0, []);

            return combinations;
        },

        comboKey(optionIds) {
            return [...(optionIds ?? [])].map(String).sort().join('-');
        },

        generateRowSku(optionIds) {
            const productSku = (this.formData.sku || '').trim();
            const optionCodes = (optionIds ?? []).map((optionId) => {
                const option = this.findCatalogOption(optionId);

                return option?.code ? String(option.code).trim().toLowerCase() : '';
            }).filter(Boolean);

            if (productSku && optionCodes.length > 0) {
                return `${productSku}-${optionCodes.join('-')}`;
            }

            return productSku || optionCodes.join('-') || '';
        },

        findCatalogOption(optionId) {
            for (const variant of this.catalogVariants) {
                const option = (variant.options ?? []).find((opt) => String(opt.id) === String(optionId));
                if (option) {
                    return option;
                }
            }

            return null;
        },

        optionLabelsForIds(optionIds) {
            const labels = { en: [], ar: [] };

            (optionIds ?? []).forEach((optionId) => {
                const option = this.findCatalogOption(optionId);
                if (!option) {
                    return;
                }

                labels.en.push(option.name_en ?? option.name ?? '');
                labels.ar.push(option.name_ar ?? option.name ?? '');
            });

            return {
                en: labels.en.filter(Boolean).join(' / '),
                ar: labels.ar.filter(Boolean).join(' / '),
            };
        },

        normalizeVariantRow(row = {}) {
            const optionsByVariant = { ...(row.options_by_variant ?? {}) };

            this.catalogVariants.forEach((variant) => {
                const key = String(variant.id);
                if (!optionsByVariant[key] && Array.isArray(row.option_ids)) {
                    const match = row.option_ids.find((optionId) => (
                        variant.options?.some((opt) => String(opt.id) === String(optionId))
                    ));
                    if (match) {
                        optionsByVariant[key] = String(match);
                    }
                }
                if (!optionsByVariant[key]) {
                    optionsByVariant[key] = '';
                }
            });

            const optionIds = Object.values(optionsByVariant)
                .filter((value) => value !== '' && value != null)
                .map((value) => String(value));

            const labels = this.optionLabelsForIds(optionIds);

            return {
                _key: row._key ?? `pv_${this.comboKey(optionIds)}`,
                id: row.id ? String(row.id) : '',
                name: row.name ?? labels.en ?? labels.ar ?? '',
                sku: row.sku ?? '',
                name_en: row.name_en ?? '',
                name_ar: row.name_ar ?? '',
                price: row.price ?? '0',
                stock: row.stock ?? '',
                is_in_stock: row.is_in_stock !== false && row.is_in_stock !== '0',
                discount: row.discount ?? '0',
                discount_type: row.discount_type ?? 'percentage',
                is_active: row.is_active !== false && row.is_active !== '0',
                thumbnailPreview: row.thumbnail_preview ?? row.thumbnailPreview ?? null,
                thumbnailFile: row.thumbnailFile ?? null,
                options_by_variant: optionsByVariant,
                option_ids: optionIds,
            };
        },

        generateSlug() {
            const nameEn = (this.formData.name_en || '').toString();
            this.formData.slug = nameEn
                .toLowerCase()
                .trim()
                .replace(/[^\w\s-]/g, '')
                .replace(/[\s_-]+/g, '-')
                .replace(/^-+|-+$/g, '');
        },

        onTypeChange() {
            if (this.formData.type === 'variable') {
                this.initializeVariantOptions();
                this.generateProductVariants();
            } else {
                this.productVariants = [];
                this.formData.variantOptions = {};
                this.initializeVariantOptions();

                if (!this.isEdit && !this.formData.sku?.trim()) {
                    this.loadNextSku();
                }
            }
        },

        onNameEnInput() {
            if (!this.isEdit) {
                this.generateSlug();
            }
        },

        onSkuInput() {
            this.skuAutoGenerated = false;

            if (this.formData.type === 'variable' && this.productVariants.length > 0) {
                this.generateProductVariants();
            }
        },

        handleVariationThumbnailChange(index, event) {
            const file = event.target.files?.[0];
            if (!file || !file.type.startsWith('image/')) {
                return;
            }

            const reader = new FileReader();
            reader.onload = (e) => {
                this.productVariants = this.productVariants.map((row, rowIndex) => (
                    rowIndex === index
                        ? { ...row, thumbnailFile: file, thumbnailPreview: e.target.result }
                        : row
                ));
            };
            reader.readAsDataURL(file);
        },

        removeVariationThumbnail(index) {
            this.productVariants = this.productVariants.map((row, rowIndex) => (
                rowIndex === index
                    ? { ...row, thumbnailPreview: null, thumbnailFile: null }
                    : row
            ));

            const input = document.getElementById(`product_variant_thumbnail_${index}`);
            if (input) {
                input.value = '';
            }
        },

        handleThumbnailChange(event) {
            const file = event.target.files?.[0];
            if (!file || !file.type.startsWith('image/')) {
                return;
            }

            this.thumbnailFile = file;
            const reader = new FileReader();
            reader.onload = (e) => {
                this.thumbnailPreview = e.target.result;
            };
            reader.readAsDataURL(file);
        },

        removeThumbnail() {
            this.thumbnailPreview = null;
            this.thumbnailFile = null;
            const input = this.$refs.thumbnailInput ?? document.getElementById('thumbnail');
            if (input) {
                input.value = '';
            }
        },

        handleImagesChange(event) {
            const files = Array.from(event.target.files || []);
            files.forEach((file) => {
                if (!file.type.startsWith('image/')) {
                    return;
                }

                const reader = new FileReader();
                reader.onload = (e) => {
                    this.selectedImages.push({
                        file,
                        preview: e.target.result,
                    });
                };
                reader.readAsDataURL(file);
            });

            this.updateImagesInput();
        },

        removeImage(index) {
            this.selectedImages.splice(index, 1);
            this.updateImagesInput();
        },

        updateImagesInput() {
            const input = document.getElementById('images');
            if (!input) {
                return;
            }

            const dataTransfer = new DataTransfer();
            this.selectedImages.forEach((img) => {
                if (img.file) {
                    dataTransfer.items.add(img.file);
                }
            });
            input.files = dataTransfer.files;
        },

        syncFilesBeforeSubmit() {
            this.updateImagesInput();

            const thumbnailInput = this.$refs.thumbnailInput ?? document.getElementById('thumbnail');
            if (thumbnailInput) {
                if (this.thumbnailFile) {
                    const dataTransfer = new DataTransfer();
                    dataTransfer.items.add(this.thumbnailFile);
                    thumbnailInput.files = dataTransfer.files;
                } else {
                    thumbnailInput.value = '';
                }
            }

            this.productVariants.forEach((row, index) => {
                const input = document.getElementById(`product_variant_thumbnail_${index}`);

                if (!input) {
                    return;
                }

                if (row.thumbnailFile) {
                    const dataTransfer = new DataTransfer();
                    dataTransfer.items.add(row.thumbnailFile);
                    input.files = dataTransfer.files;
                } else {
                    input.value = '';
                }
            });
        },

        submitWizard(event) {
            event.preventDefault();

            if (!this.validateAllSteps()) {
                return;
            }

            this.syncFilesBeforeSubmit();
            event.target.submit();
        },

        validateAllSteps() {
            const savedStep = this.currentStep;
            let valid = true;

            for (let step = 1; step <= this.totalSteps; step += 1) {
                this.currentStep = step;

                if (!this.validateCurrentStep()) {
                    valid = false;
                    break;
                }
            }

            if (valid) {
                this.currentStep = savedStep;
            }

            return valid;
        },

        nextStep() {
            if (!this.validateCurrentStep()) {
                return;
            }

            if (this.currentStep < this.totalSteps) {
                this.currentStep += 1;
                window.scrollTo({ top: 0, behavior: 'smooth' });
            }
        },

        previousStep() {
            if (this.currentStep > 1) {
                this.currentStep -= 1;
                window.scrollTo({ top: 0, behavior: 'smooth' });
            }
        },

        goToStep(step) {
            if (step <= this.currentStep || step === this.currentStep + 1) {
                this.currentStep = step;
                window.scrollTo({ top: 0, behavior: 'smooth' });
            }
        },

        validateCurrentStep() {
            if (this.currentStepKey === 'basic') {
                return Boolean(
                    this.formData.brand_id
                    && this.formData.name_en?.trim()
                    && this.formData.name_ar?.trim()
                    && this.formData.sku?.trim()
                    && this.formData.description_en?.trim()
                    && this.formData.description_ar?.trim(),
                );
            }

            if (this.currentStepKey === 'pricing') {
                const price = parseFloat(this.formData.price);
                const stockValue = (this.formData.stock ?? '').toString().trim();
                const stockValid = stockValue === '' || (!Number.isNaN(parseInt(stockValue, 10)) && parseInt(stockValue, 10) >= 0);

                if (this.isVariable) {
                    return !Number.isNaN(price) && price >= 0;
                }

                return !Number.isNaN(price) && price >= 0 && stockValid;
            }

            if (this.currentStepKey === 'variants') {
                if (this.catalogVariants.length === 0) {
                    return false;
                }

                if (!this.hasAnyVariantOptionSelected()) {
                    return false;
                }

                if (this.productVariants.length === 0) {
                    return false;
                }

                return this.productVariants.every((row) => {
                    const hasSku = Boolean(row.sku?.trim());
                    const price = parseFloat(row.price);
                    const stockValue = (row.stock ?? '').toString().trim();
                    const stockValid = stockValue === '' || (!Number.isNaN(parseInt(stockValue, 10)) && parseInt(stockValue, 10) >= 0);
                    const optionsSelected = (row.option_ids ?? []).length > 0;

                    return hasSku
                        && optionsSelected
                        && !Number.isNaN(price) && price >= 0
                        && stockValid;
                });
            }

            return true;
        },

        canProceed() {
            return this.validateCurrentStep();
        },

        stepLabel(key) {
            const labels = {
                basic: config.labels?.basic ?? 'Basic info',
                pricing: config.labels?.pricing ?? 'Pricing and stock',
                variants: config.labels?.variants ?? 'Product variants',
                categories: config.labels?.categories ?? 'Categories',
                images: config.labels?.images ?? 'Images',
                related: config.labels?.related ?? 'Related products',
            };

            return labels[key] ?? key;
        },
    };
}
