/**
 * Admin product create/edit multi-step form.
 */

const IMAGE_EXTENSION_MIME = {
    jpg: 'image/jpeg',
    jpeg: 'image/jpeg',
    png: 'image/png',
    gif: 'image/gif',
    webp: 'image/webp',
    bmp: 'image/bmp',
    svg: 'image/svg+xml',
};

function inferImageMimeFromName(name) {
    const ext = String(name ?? '').split('.').pop()?.toLowerCase();

    return ext ? IMAGE_EXTENSION_MIME[ext] ?? null : null;
}

function isImageFile(file) {
    if (!file) {
        return false;
    }

    if (file.type?.startsWith('image/')) {
        return true;
    }

    return inferImageMimeFromName(file.name) !== null;
}

function fileSubmitName(file) {
    const name = String(file?.name ?? '').trim();

    if (/\.(jpe?g|png|gif|webp|bmp)$/i.test(name)) {
        return name;
    }

    const mime = file.type || inferImageMimeFromName(name) || 'image/jpeg';
    const extension = mime === 'image/jpeg'
        ? 'jpg'
        : mime.replace('image/', '').replace('x-ms-', '') || 'jpg';

    return `image.${extension}`;
}

function stripWizardFileFields(formData, variantCount) {
    formData.delete('thumbnail');

    while (formData.has('images[]')) {
        formData.delete('images[]');
    }

    for (let index = 0; index < variantCount; index += 1) {
        formData.delete(`product_variants[${index}][thumbnail]`);
    }
}

function appendWizardFileField(formData, fieldName, file) {
    if (!file) {
        return;
    }

    formData.append(fieldName, file, fileSubmitName(file));
}

function buildWizardFormData(form, wizard) {
    const formData = new FormData(form);

    stripWizardFileFields(formData, wizard.productVariants.length);

    appendWizardFileField(formData, 'thumbnail', wizard.thumbnailFile);

    wizard.selectedImages.forEach((image) => {
        appendWizardFileField(formData, 'images[]', image.file);
    });

    wizard.productVariants.forEach((row, index) => {
        appendWizardFileField(formData, `product_variants[${index}][thumbnail]`, row.thumbnailFile);
    });

    return formData;
}

export function productWizard(config = {}) {
    const formData = {
        type: 'simple',
        brand_id: '',
        name_en: '',
        name_ar: '',
        slug: '',
        sku: '',
        description_en: '',
        description_ar: '',
        is_in_stock: true,
        discount: '0',
        discount_type: 'percentage',
        category_ids: [],
        related_products: [],
        is_active: true,
        is_featured: false,
        is_new: false,
        is_approved: true,
        is_bookable: false,
        variantOptions: {},
        ...(config.formData ?? {}),
    };

    if (!formData.variantOptions || typeof formData.variantOptions !== 'object') {
        formData.variantOptions = {};
    }

    const catalogVariants = config.catalogVariants ?? [];
    const catalogUnits = (config.catalogUnits ?? []).map((unit) => ({
        ...unit,
        id: String(unit.id ?? ''),
        name: unit.name ?? '',
        code: unit.code ?? '',
    }));
    const initialRows = config.existingProductVariants ?? [];
    const initialUnitRows = config.existingProductUnits ?? [];
    const quickCatalogVariantUrl = config.quickCatalogVariantUrl ?? '';
    const quickVariantOptionUrl = config.quickVariantOptionUrl ?? '';
    const quickCatalogUnitUrl = config.quickCatalogUnitUrl ?? '';
    const nextSkuUrl = config.nextSkuUrl ?? '';
    const validationErrorKeys = config.validationErrorKeys ?? [];

    return {
        mode: config.mode ?? 'create',
        currentStep: 1,
        formData,
        catalogVariants,
        catalogUnits,
        productVariants: [],
        productUnits: [],
        optionSearchQueries: {},
        newOptionForms: {},
        newCatalogVariant: { name_en: '', name_ar: '' },
        newCatalogUnit: { name_en: '', name_ar: '', code: '' },
        catalogVariantSaving: false,
        catalogUnitSaving: false,
        catalogUnitError: null,
        optionSavingId: null,
        skuAutoGenerated: false,
        validationMessage: null,
        quickCatalogVariantUrl,
        quickVariantOptionUrl,
        quickCatalogUnitUrl,
        nextSkuUrl,
        thumbnailPreview: config.thumbnailPreview ?? null,
        thumbnailFile: null,
        selectedImages: [],
        existingImages: config.existingImages ?? [],

        get isEdit() {
            return this.mode === 'edit';
        },

        get isVariable() {
            return this.formData.type === 'variable';
        },

        get stepFlow() {
            const steps = ['basic', 'pricing'];
            if (this.isVariable) {
                steps.push('variants');
            }
            steps.push('categories', 'images', 'related');

            return steps;
        },

        get totalSteps() {
            return this.stepFlow.length;
        },

        get currentStepKey() {
            return this.stepFlow[this.currentStep - 1] ?? 'basic';
        },

        init() {
            if (this.formData.name_en && !this.isEdit) {
                this.generateSlug();
            }

            this.initializeVariantOptions();
            this.initializeOptionForms();

            if (!this.isEdit) {
                this.loadNextSku();
            }

            if (initialRows.length > 0) {
                this.rebuildVariantOptionsFromRows(initialRows);
                this.generateProductVariants(initialRows);
            }

            if (initialUnitRows.length > 0) {
                this.productUnits = initialUnitRows.map((row) => this.normalizeProductUnitRow(row));
                this.ensureCatalogUnitsForProductRows();
                this.refreshProductUnitSkus();
            } else if (!this.isVariable) {
                this.addProductUnitRow();
            }

            this.focusStepForValidationErrors();
        },

        focusStepForValidationErrors() {
            if (validationErrorKeys.length === 0) {
                return;
            }

            const stepKeyForField = (field) => {
                if (field === 'thumbnail' || field.startsWith('images')) {
                    return 'images';
                }

                if (field.startsWith('product_variants')) {
                    return 'variants';
                }

                if (field.startsWith('category_ids')) {
                    return 'categories';
                }

                if (field.startsWith('related_products')) {
                    return 'related';
                }

                if (
                    field.startsWith('product_units')
                    || field === 'discount'
                    || field === 'discount_type'
                    || field === 'is_in_stock'
                ) {
                    return 'pricing';
                }

                return 'basic';
            };

            for (const field of validationErrorKeys) {
                const stepKey = stepKeyForField(field);
                const stepIndex = this.stepFlow.indexOf(stepKey);

                if (stepIndex >= 0) {
                    this.currentStep = stepIndex + 1;
                    break;
                }
            }
        },

        ensureCatalogUnitsForProductRows() {
            const knownIds = new Set(
                (this.catalogUnits ?? []).map((unit) => String(unit.id)),
            );

            for (const row of this.productUnits) {
                const unitId = row.unit_id ? String(row.unit_id) : '';

                if (!unitId || knownIds.has(unitId)) {
                    continue;
                }

                const unit = {
                    id: unitId,
                    code: row.unit_code ?? '',
                    name: row.unit_name || `Unit #${unitId}`,
                };

                this.catalogUnits.push(unit);
                knownIds.add(unitId);
            }
        },

        applyNewCatalogUnitToRows(unitId) {
            const id = String(unitId ?? '').trim();

            if (!id) {
                return;
            }

            let targetIndex = this.productUnits.findIndex((row) => !row.unit_id);

            if (targetIndex < 0 && this.productUnits.length > 0) {
                targetIndex = this.productUnits.length - 1;
            }

            if (targetIndex < 0) {
                if (this.isVariable) {
                    this.addVariantUnitRow();
                } else {
                    this.addProductUnitRow();
                }

                targetIndex = this.productUnits.length - 1;
            }

            this.productUnits[targetIndex].unit_id = id;

            if (this.isVariable) {
                this.refreshVariantUnitRowSku(targetIndex);
            } else {
                this.refreshProductUnitRowSku(targetIndex);
            }
        },

        defaultPieceUnitId() {
            const piece = (this.catalogUnits ?? []).find((unit) => unit.code === 'piece');

            if (piece?.id) {
                return String(piece.id);
            }

            return this.catalogUnits[0]?.id ? String(this.catalogUnits[0].id) : '';
        },

        normalizeProductUnitRow(row) {
            const variantOptionIds = (row.variant_option_ids ?? [])
                .map((id) => String(id))
                .filter(Boolean);
            const variantKey = row.variant_key
                ? String(row.variant_key)
                : (variantOptionIds.length > 0 ? this.comboKey(variantOptionIds) : '');

            return {
                id: row.id ? String(row.id) : '',
                product_variant_id: row.product_variant_id ? String(row.product_variant_id) : '',
                variant_option_ids: variantOptionIds,
                variant_key: variantKey,
                unit_id: row.unit_id !== null && row.unit_id !== undefined && String(row.unit_id) !== ''
                    ? String(row.unit_id)
                    : '',
                unit_code: row.unit_code ?? '',
                unit_name: row.unit_name ?? '',
                sku: row.sku ?? '',
                unitSkuAutoGenerated: row.unitSkuAutoGenerated === true,
                price: row.price ?? '0',
                stock: row.stock ?? '',
                is_in_stock: row.is_in_stock !== false && row.is_in_stock !== '0',
                factor: row.factor ? String(row.factor) : '1',
                discount: row.discount ?? '0',
                discount_type: row.discount_type ?? 'percentage',
                is_default: row.is_default === true || row.is_default === 1 || row.is_default === '1',
                is_active: row.is_active !== false && row.is_active !== '0',
                sort_order: row.sort_order ? String(row.sort_order) : '0',
            };
        },

        addProductUnitRow() {
            const isFirst = this.productUnits.length === 0;
            const defaultUnitId = this.defaultPieceUnitId();

            this.productUnits.push({
                id: '',
                unit_id: defaultUnitId,
                sku: this.generateProductUnitSku(defaultUnitId),
                unitSkuAutoGenerated: !this.isEdit,
                price: '0',
                stock: '',
                is_in_stock: true,
                factor: '1',
                discount: this.formData.discount ?? '0',
                discount_type: this.formData.discount_type ?? 'percentage',
                is_default: isFirst,
                is_active: true,
                sort_order: String(this.productUnits.length),
            });
        },

        removeProductUnitRow(index) {
            if (!this.isVariable && this.productUnits.length <= 1) {
                return;
            }

            this.productUnits = this.productUnits.filter((_, rowIndex) => rowIndex !== index);

            if (this.productUnits.length > 0 && !this.productUnits.some((row) => row.is_default)) {
                this.productUnits[0].is_default = true;
            }
        },

        findProductVariantByKey(variantKey) {
            const key = String(variantKey ?? '').trim();

            if (!key) {
                return null;
            }

            return this.productVariants.find((variant) => (
                this.comboKey(variant.option_ids) === key
                || variant._key === `pv_${key}`
            )) ?? null;
        },

        addVariantUnitRow() {
            const firstVariant = this.productVariants[0] ?? null;
            const variantKey = firstVariant ? this.comboKey(firstVariant.option_ids) : '';
            const isFirst = this.productUnits.length === 0;
            const defaultUnitId = this.defaultPieceUnitId();

            this.productUnits.push({
                id: '',
                product_variant_id: firstVariant?.id ? String(firstVariant.id) : '',
                variant_option_ids: firstVariant ? [...firstVariant.option_ids] : [],
                variant_key: variantKey,
                unit_id: defaultUnitId,
                sku: firstVariant ? this.generateVariantUnitSku(firstVariant, defaultUnitId) : '',
                price: '0',
                stock: '',
                is_in_stock: true,
                factor: '1',
                discount: this.formData.discount ?? '0',
                discount_type: this.formData.discount_type ?? 'percentage',
                is_default: isFirst,
                is_active: true,
                sort_order: String(this.productUnits.length),
            });
        },

        syncVariantUnitRow(index) {
            const row = this.productUnits[index];

            if (!row) {
                return;
            }

            const variant = this.findProductVariantByKey(row.variant_key);

            if (!variant) {
                row.product_variant_id = '';
                row.variant_option_ids = [];
                return;
            }

            row.product_variant_id = variant.id ? String(variant.id) : '';
            row.variant_option_ids = [...variant.option_ids];
            row.variant_key = this.comboKey(variant.option_ids);

            const autoSku = this.generateVariantUnitSku(variant, row.unit_id);

            if (this.shouldRefreshAutoSku(row.sku, autoSku)) {
                row.sku = autoSku;
            }
        },

        generateVariantUnitSku(variant, unitId) {
            const variantSku = (variant?.sku || '').trim();
            const unitCode = this.findCatalogUnit(unitId)?.code
                ? String(this.findCatalogUnit(unitId).code).trim().toLowerCase()
                : '';

            if (variantSku && unitCode) {
                return `${variantSku}-${unitCode}`;
            }

            return this.generateProductUnitSku(unitId);
        },

        refreshVariantUnitRowSku(index) {
            const row = this.productUnits[index];

            if (!row) {
                return;
            }

            const variant = this.findProductVariantByKey(row.variant_key);
            const autoSku = variant
                ? this.generateVariantUnitSku(variant, row.unit_id)
                : this.generateProductUnitSku(row.unit_id);

            if (this.shouldRefreshAutoSku(row.sku, autoSku)) {
                row.sku = autoSku;
            }
        },

        syncProductUnitsWithVariants() {
            if (!this.isVariable) {
                return;
            }

            const validKeys = new Set(
                this.productVariants.map((variant) => this.comboKey(variant.option_ids)),
            );

            this.productUnits = this.productUnits
                .filter((row) => {
                    const key = row.variant_key || this.comboKey(row.variant_option_ids ?? []);

                    return key !== '' && validKeys.has(key);
                })
                .map((row) => {
                    const key = row.variant_key || this.comboKey(row.variant_option_ids ?? []);
                    const variant = this.findProductVariantByKey(key);

                    if (!variant) {
                        return row;
                    }

                    const autoSku = this.generateVariantUnitSku(variant, row.unit_id);

                    return {
                        ...row,
                        variant_key: key,
                        variant_option_ids: [...variant.option_ids],
                        product_variant_id: variant.id ? String(variant.id) : '',
                        sku: this.shouldRefreshAutoSku(row.sku, autoSku) ? autoSku : row.sku,
                    };
                });
        },

        setDefaultProductUnit(index) {
            this.productUnits = this.productUnits.map((row, rowIndex) => ({
                ...row,
                is_default: rowIndex === index,
            }));
        },

        initializeVariantOptions() {
            const options = { ...(this.formData.variantOptions ?? {}) };

            this.catalogVariants.forEach((variant) => {
                const key = String(variant.id);
                if (!Array.isArray(options[key])) {
                    options[key] = [];
                }
            });

            this.formData.variantOptions = options;
        },

        initializeOptionForms() {
            const forms = { ...(this.newOptionForms ?? {}) };
            const queries = { ...(this.optionSearchQueries ?? {}) };

            this.catalogVariants.forEach((variant) => {
                const key = String(variant.id);
                if (!forms[key]) {
                    forms[key] = { name_en: '', name_ar: '' };
                }
                if (queries[key] === undefined) {
                    queries[key] = '';
                }
            });

            this.newOptionForms = forms;
            this.optionSearchQueries = queries;
        },

        csrfToken() {
            return document.querySelector('meta[name="csrf-token"]')?.content ?? '';
        },

        async loadNextSku() {
            if (!this.nextSkuUrl || this.isEdit) {
                return;
            }

            try {
                const response = await fetch(this.nextSkuUrl, {
                    headers: { Accept: 'application/json' },
                });

                if (!response.ok) {
                    return;
                }

                const payload = await response.json();

                if (payload.sku) {
                    this.formData.sku = payload.sku;
                    this.skuAutoGenerated = true;

                    if (this.formData.type === 'variable') {
                        this.generateProductVariants();
                    } else {
                        this.refreshProductUnitSkus(true);
                    }
                }
            } catch {
                // Keep manual entry available if the request fails.
            }
        },

        isOptionSelected(variantId, optionId) {
            return this.isVariantOptionSelected(variantId, optionId);
        },

        optionLabel(optionId) {
            const option = this.findCatalogOption(optionId);

            return option?.name ?? option?.name_en ?? `#${optionId}`;
        },

        filteredCatalogOptions(catalogVariant) {
            const query = (this.optionSearchQueries[String(catalogVariant.id)] ?? '').trim().toLowerCase();
            const options = catalogVariant.options ?? [];

            if (!query) {
                return options;
            }

            return options.filter((option) => {
                const haystack = [
                    option.name,
                    option.name_en,
                    option.name_ar,
                    option.code,
                ].filter(Boolean).join(' ').toLowerCase();

                return haystack.includes(query);
            });
        },

        async createCatalogUnit() {
            const nameEn = (this.newCatalogUnit.name_en ?? '').trim();
            const nameAr = (this.newCatalogUnit.name_ar ?? '').trim();
            const code = (this.newCatalogUnit.code ?? '').trim();

            this.catalogUnitError = null;

            if (!nameEn || !nameAr) {
                this.catalogUnitError = 'Please enter English and Arabic unit names.';

                return;
            }

            if (!this.quickCatalogUnitUrl) {
                return;
            }

            this.catalogUnitSaving = true;

            try {
                const response = await fetch(this.quickCatalogUnitUrl, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        Accept: 'application/json',
                        'X-CSRF-TOKEN': this.csrfToken(),
                    },
                    body: JSON.stringify({
                        name: { en: nameEn, ar: nameAr },
                        ...(code ? { code } : {}),
                    }),
                });

                const payload = await response.json().catch(() => ({}));

                if (!response.ok) {
                    const firstError = Object.values(payload.errors ?? {})[0]?.[0];

                    this.catalogUnitError = firstError || payload.message || 'Could not create unit.';

                    return;
                }

                if (payload.unit) {
                    const unit = {
                        ...payload.unit,
                        id: String(payload.unit.id ?? ''),
                        name: payload.unit.name ?? payload.unit.name_en ?? nameEn,
                        code: payload.unit.code ?? '',
                    };

                    const exists = (this.catalogUnits ?? []).some(
                        (row) => String(row.id) === String(unit.id),
                    );

                    if (!exists) {
                        this.catalogUnits = [...this.catalogUnits, unit];
                    }

                    this.applyNewCatalogUnitToRows(unit.id);
                    this.newCatalogUnit = { name_en: '', name_ar: '', code: '' };
                }
            } catch {
                this.catalogUnitError = 'Could not create unit.';
            } finally {
                this.catalogUnitSaving = false;
            }
        },

        async createCatalogVariant() {
            const nameEn = (this.newCatalogVariant.name_en ?? '').trim();
            const nameAr = (this.newCatalogVariant.name_ar ?? '').trim();

            if (!nameEn || !nameAr || !this.quickCatalogVariantUrl) {
                return;
            }

            this.catalogVariantSaving = true;

            try {
                const response = await fetch(this.quickCatalogVariantUrl, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        Accept: 'application/json',
                        'X-CSRF-TOKEN': this.csrfToken(),
                    },
                    body: JSON.stringify({
                        name: { en: nameEn, ar: nameAr },
                    }),
                });

                if (!response.ok) {
                    return;
                }

                const payload = await response.json();
                this.catalogVariants = [...this.catalogVariants, payload.variant];
                this.newCatalogVariant = { name_en: '', name_ar: '' };
                this.initializeVariantOptions();
                this.initializeOptionForms();
            } finally {
                this.catalogVariantSaving = false;
            }
        },

        async createCatalogOption(variantId) {
            const key = String(variantId);
            const form = this.newOptionForms[key] ?? { name_en: '', name_ar: '' };
            const nameEn = (form.name_en ?? '').trim();
            const nameAr = (form.name_ar ?? '').trim();

            if (!nameEn || !nameAr || !this.quickVariantOptionUrl) {
                return;
            }

            this.optionSavingId = key;

            try {
                const response = await fetch(this.quickVariantOptionUrl, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        Accept: 'application/json',
                        'X-CSRF-TOKEN': this.csrfToken(),
                    },
                    body: JSON.stringify({
                        variant_id: Number(variantId),
                        name: { en: nameEn, ar: nameAr },
                    }),
                });

                if (!response.ok) {
                    return;
                }

                const payload = await response.json();
                this.catalogVariants = this.catalogVariants.map((variant) => {
                    if (String(variant.id) !== String(payload.variant_id)) {
                        return variant;
                    }

                    const options = [...(variant.options ?? []), payload.option];

                    return { ...variant, options };
                });

                this.newOptionForms[key] = { name_en: '', name_ar: '' };
                this.toggleVariantOption(variantId, payload.option.id, true);
            } finally {
                this.optionSavingId = null;
            }
        },

        rebuildVariantOptionsFromRows(rows) {
            this.initializeVariantOptions();

            rows.forEach((row) => {
                const optionIds = row.option_ids ?? Object.values(row.options_by_variant ?? {}).filter(Boolean);

                optionIds.forEach((optionId) => {
                    const catalogVariant = this.catalogVariants.find((variant) => (
                        variant.options?.some((opt) => String(opt.id) === String(optionId))
                    ));

                    if (!catalogVariant) {
                        return;
                    }

                    const variantId = String(catalogVariant.id);
                    const optionIdStr = String(optionId);

                    if (!this.formData.variantOptions[variantId].includes(optionIdStr)) {
                        this.formData.variantOptions[variantId].push(optionIdStr);
                    }
                });
            });
        },

        isVariantOptionSelected(variantId, optionId) {
            const selected = this.formData.variantOptions[String(variantId)] ?? [];

            return selected.map(String).includes(String(optionId));
        },

        hasAnyVariantOptionSelected() {
            return Object.values(this.formData.variantOptions ?? {}).some(
                (options) => Array.isArray(options) && options.length > 0,
            );
        },

        toggleVariantOption(variantId, optionId, isChecked) {
            const variantKey = String(variantId);

            if (!this.formData.variantOptions[variantKey]) {
                this.formData.variantOptions = {
                    ...this.formData.variantOptions,
                    [variantKey]: [],
                };
            }

            const optionIdStr = String(optionId);
            const currentOptions = [...(this.formData.variantOptions[variantKey] ?? [])];

            if (isChecked) {
                if (!currentOptions.includes(optionIdStr)) {
                    this.formData.variantOptions[variantKey] = [...currentOptions, optionIdStr];
                }
            } else {
                this.formData.variantOptions[variantKey] = currentOptions.filter((id) => id !== optionIdStr);
            }

            this.generateProductVariants();
        },

        generateProductVariants(seedRows = null) {
            if (this.formData.type !== 'variable') {
                this.productVariants = [];

                return;
            }

            if (!this.hasAnyVariantOptionSelected()) {
                this.productVariants = [];

                return;
            }

            const existingByCombo = {};
            const sourceRows = seedRows ?? this.productVariants;

            sourceRows.forEach((row) => {
                const normalized = this.normalizeVariantRow(row);
                const key = this.comboKey(normalized.option_ids);

                if (key) {
                    existingByCombo[key] = normalized;
                }
            });

            const combinations = this.buildVariantCombinations();

            const nextVariants = combinations.map((combo) => {
                const key = this.comboKey(combo.option_ids);
                const existing = existingByCombo[key];
                const autoSku = this.generateRowSku(combo.option_ids);
                const labels = this.optionLabelsForIds(combo.option_ids);
                const displayName = labels.en || labels.ar || '';

                if (existing) {
                    const previousAutoSku = this.generateRowSku(existing.option_ids ?? []);
                    const shouldRefreshSku = !existing.sku?.trim()
                        || existing.sku === previousAutoSku
                        || (this.formData.sku && String(existing.sku).startsWith(`${this.formData.sku}-`));

                    return {
                        ...existing,
                        _key: `pv_${key}`,
                        option_ids: combo.option_ids,
                        options_by_variant: combo.options_by_variant,
                        name: existing.name || displayName,
                        name_en: existing.name_en || labels.en,
                        name_ar: existing.name_ar || labels.ar,
                        sku: shouldRefreshSku ? autoSku : existing.sku,
                    };
                }

                return {
                    _key: `pv_${key}`,
                    id: '',
                    name: displayName,
                    sku: autoSku,
                    name_en: labels.en,
                    name_ar: labels.ar,
                    price: '0',
                    stock: '',
                    is_in_stock: true,
                    discount: '0',
                    discount_type: 'percentage',
                    is_active: true,
                    thumbnailPreview: null,
                    thumbnailFile: null,
                    options_by_variant: combo.options_by_variant,
                    option_ids: combo.option_ids,
                };
            });

            this.productVariants = nextVariants;
            this.syncProductUnitsWithVariants();
        },

        buildVariantCombinations() {
            const variantsWithOptions = this.catalogVariants.filter((variant) => {
                const selected = this.formData.variantOptions[String(variant.id)] ?? [];

                return selected.length > 0;
            });

            if (variantsWithOptions.length === 0) {
                return [];
            }

            const optionArrays = variantsWithOptions.map((variant) => {
                const selectedOptionIds = (this.formData.variantOptions[String(variant.id)] ?? [])
                    .map((id) => String(id));

                return (variant.options ?? []).filter((option) => selectedOptionIds.includes(String(option.id)));
            });

            const combinations = [];

            const generate = (index, current) => {
                if (index === optionArrays.length) {
                    const optionIds = current.map((option) => String(option.id));
                    const optionsByVariant = {};

                    current.forEach((option, optionIndex) => {
                        const variant = variantsWithOptions[optionIndex];
                        optionsByVariant[String(variant.id)] = String(option.id);
                    });

                    combinations.push({
                        option_ids: optionIds,
                        options_by_variant: optionsByVariant,
                    });

                    return;
                }

                optionArrays[index].forEach((option) => {
                    generate(index + 1, [...current, option]);
                });
            };

            generate(0, []);

            return combinations;
        },

        comboKey(optionIds) {
            return [...(optionIds ?? [])].map(String).sort().join('-');
        },

        generateRowSku(optionIds) {
            const productSku = (this.formData.sku || '').trim();
            const optionCodes = (optionIds ?? []).map((optionId) => {
                const option = this.findCatalogOption(optionId);

                return option?.code ? String(option.code).trim().toLowerCase() : '';
            }).filter(Boolean);

            if (productSku && optionCodes.length > 0) {
                return `${productSku}-${optionCodes.join('-')}`;
            }

            return productSku || optionCodes.join('-') || '';
        },

        findCatalogUnit(unitId) {
            return (this.catalogUnits ?? []).find((unit) => String(unit.id) === String(unitId)) ?? null;
        },

        generateProductUnitSku(unitId) {
            const productSku = (this.formData.sku || '').trim();
            const unit = this.findCatalogUnit(unitId);
            const unitCode = unit?.code ? String(unit.code).trim().toLowerCase() : '';

            if (productSku && unitCode) {
                return `${productSku}-${unitCode}`;
            }

            return productSku || unitCode || '';
        },

        shouldRefreshAutoSku(currentSku, autoSku = null) {
            const sku = (currentSku ?? '').trim();

            if (!sku) {
                return true;
            }

            if (autoSku && sku === autoSku) {
                return true;
            }

            const productSku = (this.formData.sku || '').trim();

            return productSku !== '' && sku.startsWith(`${productSku}-`);
        },

        shouldRefreshStaleUnitSku(row) {
            if (this.isEdit || !this.skuAutoGenerated) {
                return false;
            }

            const sku = String(row.sku ?? '').trim();
            const unitCode = this.findCatalogUnit(row.unit_id)?.code
                ? String(this.findCatalogUnit(row.unit_id).code).trim().toLowerCase()
                : '';

            return unitCode !== '' && sku === unitCode;
        },

        refreshProductUnitSkus(force = false) {
            if (this.productUnits.length === 0) {
                return;
            }

            this.productUnits = this.productUnits.map((row) => {
                const autoSku = this.generateProductUnitSku(row.unit_id);
                const shouldAuto = force
                    || row.unitSkuAutoGenerated
                    || this.shouldRefreshAutoSku(row.sku, autoSku)
                    || this.shouldRefreshStaleUnitSku(row);

                if (!shouldAuto) {
                    return row;
                }

                return {
                    ...row,
                    sku: autoSku,
                    unitSkuAutoGenerated: !this.isEdit,
                };
            });
        },

        refreshProductUnitRowSku(index) {
            const row = this.productUnits[index];

            if (!row) {
                return;
            }

            const autoSku = this.generateProductUnitSku(row.unit_id);

            if (
                row.unitSkuAutoGenerated
                || this.shouldRefreshAutoSku(row.sku, autoSku)
                || this.shouldRefreshStaleUnitSku(row)
            ) {
                row.sku = autoSku;
                row.unitSkuAutoGenerated = !this.isEdit;
            }
        },

        onProductUnitSkuInput(index) {
            const row = this.productUnits[index];

            if (row) {
                row.unitSkuAutoGenerated = false;
            }
        },

        findCatalogOption(optionId) {
            for (const variant of this.catalogVariants) {
                const option = (variant.options ?? []).find((opt) => String(opt.id) === String(optionId));
                if (option) {
                    return option;
                }
            }

            return null;
        },

        optionLabelsForIds(optionIds) {
            const labels = { en: [], ar: [] };

            (optionIds ?? []).forEach((optionId) => {
                const option = this.findCatalogOption(optionId);
                if (!option) {
                    return;
                }

                labels.en.push(option.name_en ?? option.name ?? '');
                labels.ar.push(option.name_ar ?? option.name ?? '');
            });

            return {
                en: labels.en.filter(Boolean).join(' / '),
                ar: labels.ar.filter(Boolean).join(' / '),
            };
        },

        normalizeVariantRow(row = {}) {
            const optionsByVariant = { ...(row.options_by_variant ?? {}) };

            this.catalogVariants.forEach((variant) => {
                const key = String(variant.id);
                if (!optionsByVariant[key] && Array.isArray(row.option_ids)) {
                    const match = row.option_ids.find((optionId) => (
                        variant.options?.some((opt) => String(opt.id) === String(optionId))
                    ));
                    if (match) {
                        optionsByVariant[key] = String(match);
                    }
                }
                if (!optionsByVariant[key]) {
                    optionsByVariant[key] = '';
                }
            });

            const optionIds = Object.values(optionsByVariant)
                .filter((value) => value !== '' && value != null)
                .map((value) => String(value));

            const labels = this.optionLabelsForIds(optionIds);

            return {
                _key: row._key ?? `pv_${this.comboKey(optionIds)}`,
                id: row.id ? String(row.id) : '',
                name: row.name ?? labels.en ?? labels.ar ?? '',
                sku: row.sku ?? '',
                name_en: row.name_en ?? '',
                name_ar: row.name_ar ?? '',
                price: row.price ?? '0',
                stock: row.stock ?? '',
                is_in_stock: row.is_in_stock !== false && row.is_in_stock !== '0',
                discount: row.discount ?? '0',
                discount_type: row.discount_type ?? 'percentage',
                is_active: row.is_active !== false && row.is_active !== '0',
                thumbnailPreview: row.thumbnail_preview ?? row.thumbnailPreview ?? null,
                thumbnailFile: row.thumbnailFile ?? null,
                options_by_variant: optionsByVariant,
                option_ids: optionIds,
            };
        },

        generateSlug() {
            const nameEn = (this.formData.name_en || '').toString();
            this.formData.slug = nameEn
                .toLowerCase()
                .trim()
                .replace(/[^\w\s-]/g, '')
                .replace(/[\s_-]+/g, '-')
                .replace(/^-+|-+$/g, '');
        },

        onTypeChange() {
            if (this.formData.type === 'variable') {
                this.initializeVariantOptions();
                this.productUnits = this.productUnits.filter((row) => {
                    const key = row.variant_key || this.comboKey(row.variant_option_ids ?? []);

                    return key !== '';
                });
                this.generateProductVariants();
            } else {
                this.productVariants = [];
                this.formData.variantOptions = {};
                this.initializeVariantOptions();
                this.productUnits = this.productUnits.filter((row) => {
                    const key = row.variant_key || this.comboKey(row.variant_option_ids ?? []);

                    return key === '';
                });

                if (this.productUnits.length === 0) {
                    this.addProductUnitRow();
                }

                if (!this.isEdit && !this.formData.sku?.trim()) {
                    this.loadNextSku();
                }
            }
        },

        onNameEnInput() {
            if (!this.isEdit) {
                this.generateSlug();
            }
        },

        onSkuInput() {
            this.skuAutoGenerated = false;

            if (this.formData.type === 'variable' && this.productVariants.length > 0) {
                this.generateProductVariants();
            }

            if (this.productUnits.length > 0) {
                if (this.isVariable) {
                    this.syncProductUnitsWithVariants();
                } else {
                    this.refreshProductUnitSkus();
                }
            }
        },

        variantThumbnailInput(index) {
            const root = this.$refs.persistentFileInputs;

            return root?.querySelector(`[data-variant-thumbnail-index="${index}"]`) ?? null;
        },

        openVariantThumbnailPicker(index) {
            this.variantThumbnailInput(index)?.click();
        },

        handleVariationThumbnailChange(index, event) {
            const file = event.target.files?.[0];
            if (!isImageFile(file)) {
                return;
            }

            const reader = new FileReader();
            reader.onload = (e) => {
                this.productVariants = this.productVariants.map((row, rowIndex) => (
                    rowIndex === index
                        ? { ...row, thumbnailFile: file, thumbnailPreview: e.target.result }
                        : row
                ));
            };
            reader.readAsDataURL(file);
        },

        removeVariationThumbnail(index) {
            this.productVariants = this.productVariants.map((row, rowIndex) => (
                rowIndex === index
                    ? { ...row, thumbnailPreview: null, thumbnailFile: null }
                    : row
            ));

            const input = this.variantThumbnailInput(index);
            if (input) {
                input.value = '';
            }
        },

        handleThumbnailChange(event) {
            const file = event.target.files?.[0];
            if (!isImageFile(file)) {
                return;
            }

            this.thumbnailFile = file;
            const reader = new FileReader();
            reader.onload = (e) => {
                this.thumbnailPreview = e.target.result;
            };
            reader.readAsDataURL(file);
        },

        removeThumbnail() {
            this.thumbnailPreview = null;
            this.thumbnailFile = null;
            const input = this.$refs.thumbnailInput ?? document.getElementById('thumbnail');
            if (input) {
                input.value = '';
            }
        },

        handleImagesChange(event) {
            const files = Array.from(event.target.files || []).filter(isImageFile);

            files.forEach((file) => {
                const reader = new FileReader();
                reader.onload = (e) => {
                    this.selectedImages.push({
                        file,
                        preview: e.target.result,
                    });
                };
                reader.readAsDataURL(file);
            });

            event.target.value = '';
        },

        removeImage(index) {
            this.selectedImages.splice(index, 1);
        },

        notifyValidationFailed() {
            this.validationMessage = config.labels?.completeRequiredSteps
                ?? 'Please complete all required steps before submitting.';
            window.scrollTo({ top: 0, behavior: 'smooth' });
        },

        disableInactiveProductUnitInputs(form) {
            const activeScope = this.isVariable ? 'variable' : 'simple';

            form.querySelectorAll('[data-product-units-scope]').forEach((section) => {
                const enabled = section.getAttribute('data-product-units-scope') === activeScope;

                section.querySelectorAll('[name^="product_units"]').forEach((input) => {
                    input.disabled = !enabled;
                });
            });
        },

        async submitWizard(event) {
            event.preventDefault();

            if (!this.validateAllSteps()) {
                this.notifyValidationFailed();

                return;
            }

            const form = event.target;

            if (!this.isEdit) {
                this.generateSlug();
            }

            this.validationMessage = null;
            this.disableInactiveProductUnitInputs(form);

            const token = document.querySelector('meta[name="csrf-token"]')?.getAttribute('content') ?? '';
            const formData = buildWizardFormData(form, this);

            if (!this.isEdit && this.formData.slug) {
                formData.set('slug', this.formData.slug);
            }

            const response = await fetch(form.action, {
                method: 'POST',
                body: formData,
                headers: {
                    'X-CSRF-TOKEN': token,
                    Accept: 'text/html,application/xhtml+xml',
                },
                credentials: 'same-origin',
                redirect: 'manual',
            });

            const redirectTarget = response.headers.get('Location');

            if (redirectTarget) {
                window.location.assign(redirectTarget);

                return;
            }

            if (response.type === 'opaqueredirect') {
                window.location.assign(form.action);

                return;
            }

            if (response.ok) {
                const html = await response.text();
                document.open();
                document.write(html);
                document.close();

                return;
            }

            window.location.reload();
        },

        validateAllSteps() {
            const savedStep = this.currentStep;
            let valid = true;

            for (let step = 1; step <= this.totalSteps; step += 1) {
                this.currentStep = step;

                if (!this.validateCurrentStep()) {
                    valid = false;
                    break;
                }
            }

            if (valid) {
                this.currentStep = savedStep;
            }

            return valid;
        },

        nextStep() {
            if (!this.validateCurrentStep()) {
                return;
            }

            this.validationMessage = null;

            if (this.currentStep < this.totalSteps) {
                this.currentStep += 1;
                window.scrollTo({ top: 0, behavior: 'smooth' });
            }
        },

        previousStep() {
            if (this.currentStep > 1) {
                this.currentStep -= 1;
                window.scrollTo({ top: 0, behavior: 'smooth' });
            }
        },

        goToStep(step) {
            if (step <= this.currentStep || step === this.currentStep + 1) {
                this.currentStep = step;
                window.scrollTo({ top: 0, behavior: 'smooth' });
            }
        },

        validateCurrentStep() {
            if (this.currentStepKey === 'basic') {
                return Boolean(
                    this.formData.brand_id
                    && this.formData.name_en?.trim()
                    && this.formData.name_ar?.trim()
                    && this.formData.sku?.trim()
                    && this.formData.description_en?.trim()
                    && this.formData.description_ar?.trim(),
                );
            }

            if (this.currentStepKey === 'pricing') {
                if (this.isVariable) {
                    return true;
                }

                if (this.productUnits.length === 0) {
                    return false;
                }

                return this.productUnits.every((row) => {
                    const unitPrice = parseFloat(row.price);
                    const stockRow = (row.stock ?? '').toString().trim();
                    const stockRowValid = stockRow === ''
                        || (!Number.isNaN(parseInt(stockRow, 10)) && parseInt(stockRow, 10) >= 0);
                    const factor = parseInt(row.factor, 10);
                    const discount = parseFloat(row.discount ?? '0');
                    const discountValid = !Number.isNaN(discount) && discount >= 0;

                    return Boolean(row.unit_id)
                        && !Number.isNaN(unitPrice) && unitPrice >= 0
                        && stockRowValid
                        && discountValid
                        && !Number.isNaN(factor) && factor >= 1;
                }) && this.productUnits.some((row) => row.is_default);
            }

            if (this.currentStepKey === 'variants') {
                if (this.catalogVariants.length === 0) {
                    return false;
                }

                if (!this.hasAnyVariantOptionSelected()) {
                    return false;
                }

                if (this.productVariants.length === 0) {
                    return false;
                }

                const variantsValid = this.productVariants.every((row) => {
                    const hasSku = Boolean(row.sku?.trim());
                    const optionsSelected = (row.option_ids ?? []).length > 0;

                    return hasSku && optionsSelected;
                });

                if (!variantsValid) {
                    return false;
                }

                if (this.productUnits.length === 0) {
                    return false;
                }

                return this.productUnits.every((row) => {
                    const hasVariant = Boolean(row.variant_key)
                        || (row.variant_option_ids ?? []).length > 0;
                    const unitPrice = parseFloat(row.price);
                    const stockRow = (row.stock ?? '').toString().trim();
                    const stockRowValid = stockRow === ''
                        || (!Number.isNaN(parseInt(stockRow, 10)) && parseInt(stockRow, 10) >= 0);
                    const factor = parseInt(row.factor, 10);
                    const discount = parseFloat(row.discount ?? '0');
                    const discountValid = !Number.isNaN(discount) && discount >= 0;

                    return hasVariant
                        && Boolean(row.unit_id)
                        && !Number.isNaN(unitPrice) && unitPrice >= 0
                        && stockRowValid
                        && discountValid
                        && !Number.isNaN(factor) && factor >= 1;
                }) && this.productUnits.some((row) => row.is_default);
            }

            return true;
        },

        canProceed() {
            return this.validateCurrentStep();
        },

        stepLabel(key) {
            const labels = {
                basic: config.labels?.basic ?? 'Basic info',
                pricing: config.labels?.pricing ?? 'Pricing and stock',
                variants: config.labels?.variants ?? 'Product variants',
                categories: config.labels?.categories ?? 'Categories',
                images: config.labels?.images ?? 'Images',
                related: config.labels?.related ?? 'Related products',
            };

            return labels[key] ?? key;
        },
    };
}
